const types = {
  PUT_HOTELS: 'PUT_HOTELS',
  PUT_FILTERS: 'PUT_FILTERS',
  SUBMIT_FILTERS: 'SUBMIT_FILTERS',
  PUT_FILTERED_HOTELS: 'PUT_FILTERED_HOTELS',
  RESET_FILTERS: 'RESET_FILTERS',
};

export default types;